# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
###################################################################################################
# Recyclarr Configuration Template: HD Bluray + WEB                                               #
# Updated: 2023-12-30                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
###################################################################################################

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
radarr:
  radarr:
    base_url: http://172.17.0.1:7878
    api_key: !secret radarr_api
    media_naming:
      folder: plex
      movie:
        rename: true
        standard: default
    quality_definition:
      type: movie
    quality_profiles:
      - name: 1080p
        min_format_score: 0
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEBDL-1080p
          until_score: 10000
        qualities:
          - name: WEBDL-1080p
          - name: Bluray-1080p
          - name: WEBRip-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: Bluray-576p
          - name: WEBDL-720p
          - name: WEBRip-720p
          - name: HDTV-720p
          - name: Other
            qualities:
              - Bluray-480p
              - WEBRip-480p
              - WEBDL-480p
              - SDTV
              - DVD-R
              - DVD
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    custom_formats:
    # Audio
      - trash_ids:
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (Undefined)
          - 1af239278386be2919e1bcee0bde047e # DDPlus ATMOS
          - 185f1dd7264c4562b9022d963ac37424 # DDPlus
          - 77ff61788dfe1097194fd8743d7b4524 # 5.1 Surround
        assign_scores_to:
          - name: 1080p
    # HDR
      - trash_ids:
          - 9364dd386c9b4a1100dde8264690add7 # HLG
          - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (Undefined)
          - e61e28db95d22bedcadf030b8f156d96 # HDR
          - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
          - b974a6cd08c1066250f1f177d7aa1225 # HDR10Plus
        assign_scores_to:
          - name: 1080p
    # Movie Versions
      - trash_ids:
          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: 1080p
    # Release Groups
      - trash_ids:
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
        assign_scores_to:
          - name: 1080p
    # Misc
      - trash_ids:
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          - 0d91270a7255a1e388fa85e959f359d8 # Freeleech
          - 4b900e171accbfb172729b63323ea8ca # Multi
          - 182fa1c42a2468f8488e6dcf75a81b81 # Internal
        assign_scores_to:
          - name: 1080p
    # Streaming Service
      - trash_ids:
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - f6ff65b3f4b464a79dcc75950fe20382 # CRAV
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 917d1f2c845b2b466036b0cc2d7c72a3 # FOD
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 6185878161f1e2eef9cd0641a0d09eae # IP
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - fbca986396c5e695ef7b2def3c755d01 # OViD
          - bf7e73dd1d85b12cc527dc619761c840 # Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
          - f1b0bae9bc222dab32c1b38b5a7a1088 # TVer
          - 279bda7434fd9075786de274e6c3c202 # U-NEXT
        assign_scores_to:
          - name: 1080p
    # Anime Good
      - trash_ids:
          - fb3ccc5d5cc8f77c9055d4cb4561dded # Anime BD Tier 01 (Top SeaDex Muxers)
          - 66926c8fa9312bc74ab71bf69aae4f4a # Anime BD Tier 02 (SeaDex Muxers)
          - fa857662bad28d5ff21a6e611869a0ff # Anime BD Tier 03 (SeaDex Muxers)
          - f262f1299d99b1a2263375e8fa2ddbb3 # Anime BD Tier 04 (SeaDex Muxers)
          - ca864ed93c7b431150cc6748dc34875d # Anime BD Tier 05 (Remuxes)
          - 9dce189b960fddf47891b7484ee886ca # Anime BD Tier 06 (FanSubs)
          - 1ef101b3a82646b40e0cab7fc92cd896 # Anime BD Tier 07 (P2P/Scene)
          - 6115ccd6640b978234cc47f2c1f2cadc # Anime BD Tier 08 (Mini Encodes)
          - 8167cffba4febfb9a6988ef24f274e7e # Anime Web Tier 01 (Muxers)
          - 8526c54e36b4962d340fce52ef030e76 # Anime Web Tier 02 (Top FanSubs)
          - de41e72708d2c856fa261094c85e965d # Anime Web Tier 03 (Official Subs)
          - 9edaeee9ea3bcd585da9b7c0ac3fc54f # Anime Web Tier 04 (Official Subs)
          - 22d953bbe897857b517928f3652b8dd3 # Anime Web Tier 05 (FanSubs)
          - a786fbc0eae05afe3bb51aee3c83a9d4 # Anime Web Tier 06 (FanSubs)
          - 5f400539421b8fcf71d51e6384434573 # v1
          - 3df5e6dfef4b09bb6002f732bed5b774 # v2
          - db92c27ba606996b146b57fbe6d09186 # v3
          - d4e5e842fad129a3c097bdb2d20d31a0 # v4
          - 72b1548df1ac3175ca105a9ce7043c91 # Multi-Audio
        assign_scores_to:
          - name: 1080p
    # Anime Bad
      - trash_ids:
          - 06b6542a47037d1e33b15aa3677c2365 # Anime Raws
          - b0fdc5897f68c9a68c70c25169f77447 # Anime LQ Groups
          - c259005cbaeb5ab44c06eddb4751e70c # v0
        assign_scores_to:
          - name: 1080p
    # Unwanted
      - trash_ids:
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - 0a3f082873eb454bde444150b70253cc # Extras
        assign_scores_to:
          - name: 1080p
    # Custom-200
      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
          - b23eae459cc960816f2d6ba84af45055 # Dubs Only
        assign_scores_to:
          - name: 1080p
            score: 200
    # Custom-2000
      - trash_ids:
          - 2899d84dc9372de3408e6d8cc18e9666 # x264
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: HQ
            score: 3000
    # Custom-4000
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Dual Audio
        assign_scores_to:
          - name: HQ
            score: 4000